version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: phppickem
    ports:
      - 80:80
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: php_pickem
      DB_USERNAME: app
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: php_pickem
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password